#! /bin/bash
# Copyright 2020 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
set -ex

PATH=${PATH}:${APPDIR}/bin
PATH=${PATH}:${APPDIR}/usr/bin
export PATH=${PATH}

LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APPDIR}/lib
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APPDIR}/lib/x86_64-linux-gnu
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APPDIR}/lib/x86_64-linux-gnu/darktable

LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APPDIR}/usr/lib
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APPDIR}/usr/lib/x86_64-linux-gnu
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}

XDG_DATA_DIRS=${XDG_DATA_DIRS}:${APPDIR}/share
export XDG_DATA_DIRS=${XDG_DATA_DIRS}

cd ${APPDIR}

${APPDIR}/usr/bin/darktable $@
