#! /bin/bash
set -e


LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APPDIR}/lib
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APPDIR}/lib/darktable
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}

cd ${HOME}

${APPDIR}/application/darktable \
 --datadir ${APPDIR}/share/darktable\
 --localedir ${APPDIR}/share/locale\
  $@
